### ISSUE TITLE
worker_processes should be 1?

### ISSUE THREAD

**Issue by satchamo** [solso/insomnia#1]
For this to work, it seems like the number of `worker_processes` should always be 1. The `shared_state` isn't shared between processes (at least in my tests). When you hit the API endpoint, it will update the insomnia variable on one of the processes, not all of them.

I tested this on `openresty/1.11.2.3`

**Comment by ecerroni** [comment]
I confirm the same behavior. I had to set `worker_processes` to 1 to make it work.

I am using the `openresty/openresty:alpine` docker image

**Comment by solso** [comment]
My apologies @satchamo, totally missed the notification of your issue until @ecerroni commented on it, sorry for the long time on replying to the issue,

Unfortunately I cannot reproduce the problem, I've even installed openresty/1.11.2.2 without success. I have not upgraded nginx on my work station since 2013, not very active on tinkering with nginx at the moment.

I even did a small test to see if a count was shared or not,

    worker_processes  4;
    events { worker_connections 80; }

    init_by_lua '
       shared_state = {insomnia = false, count = 0}
    ';

    location / {
       content_by_lua '
        shared_state.count = shared_state.count + 1
        ngx.say("hello "..shared_state.count)
       ';
     }

If I hit `http://localhost/`  the value of the count increases and is returned. Stress test it with 
`ab -n 10000 -c 50 http://localhost/`. Finally, check  `http://localhost/` again. The count should be 10002. So unless all requests have been served by the same worker process, the lua dict is shared across processes.

Perhaps I'm mistaken, but I thought that lua dicts created on init_by_lua were *implicitly* treated as lua shared dicts, which quoting the docs: ["shared memory zones are always shared by all the nginx worker processes in the current nginx server instance."](https://github.com/openresty/lua-nginx-module#lua_shared_dict)

It is kind of a mistery, would be good if you reproduce the small test above. I'm not doubting the issue is occurring, but I cannot reproduce. If I could I would probably explicitly use  lua_shared_dict rather than rely on the assumption that non-loca lua dicts will be mapped as such.

**Comment by satchamo** [comment]
I wasn't able to reproduce that 10002 count. Here is my complete nginx config file:

```nginx
worker_processes  4;
events { worker_connections 80; }

http {

    init_by_lua '
        shared_state = {insomnia = false, count = 0}
    ';

    server {
        location / {
            content_by_lua '
                shared_state.count = shared_state.count + 1
                ngx.say("hello "..shared_state.count)
                ';
        }
    }
}
```


And here are my test commands:
```
root@delta:~# service openresty reload
 * Reloading full-fledged web platform configuration nginx                                                  [ OK ]
root@delta:~# ab -n 10000 -c 50 http://localhost/
This is ApacheBench, Version 2.3 <$Revision: 1528965 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        openresty/1.11.2.3
Server Hostname:        localhost
Server Port:            80

Document Path:          /
Document Length:        8 bytes

Concurrency Level:      50
Time taken for tests:   0.566 seconds
Complete requests:      10000
Failed requests:        8722
   (Connect: 0, Receive: 0, Length: 8722, Exceptions: 0)
Total transferred:      1598176 bytes
HTML transferred:       108410 bytes
Requests per second:    17674.21 [#/sec] (mean)
Time per request:       2.829 [ms] (mean)
Time per request:       0.057 [ms] (mean, across all concurrent requests)
Transfer rate:          2758.45 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   0.5      1       4
Processing:     0    2   0.7      2       8
Waiting:        0    1   0.7      2       7
Total:          2    3   1.0      3      10
WARNING: The median and mean for the waiting time are not within a normal deviation
        These results are probably not that reliable.

Percentage of the requests served within a certain time (ms)
  50%      3
  66%      3
  75%      3
  80%      3
  90%      3
  95%      4
  98%      7
  99%      8
 100%     10 (longest request)
root@delta:~# curl http://localhost/
hello 9677
```


(the "failed" requests <a href="https://stackoverflow.com/questions/579450/load-testing-with-ab-fake-failed-requests-length">are irrelevant</a>)

Another way to test this is with a simple curl loop. At around the 2000+ requests mark, I hit a different process:

```
service openresty restart; while true; do curl localhost; done
...
hello 2384
hello 2385
hello 2386
hello 2387
hello 2388
hello 2389
hello 2390
hello 2391
hello 2392
hello 2393
hello 2394
hello 1
hello 2
hello 3
hello 4
hello 5
hello 6
```

**Comment by satchamo** [comment]
I think using `lua_shared_dict` will have the desired effect. This nginx conf seems to work as expected:

```
worker_processes  4;
events { worker_connections 80; }

http {
    lua_shared_dict state 12k;
    init_by_lua_block {
        local s = ngx.shared.state;
        s:set("count", 0)
    }

    server {
        location / {
            content_by_lua_block {
                local s = ngx.shared.state;
                s:set("count", s:get("count")+1);
                ngx.say("hello "..s:get("count"))
            }
        }
    }
}
```

**Comment by solso** [comment]
thanks @satchamo for checking it out. I'm really puzzled why we have different behaviour :/ totally failing to reproduce the issue,

in any case, using the `ngx.shared.state` explicitly is much safer, and it works for you too. I'll update the repo shortly. If you want to do a pull request with the fix, I'll gladly merge it, credit to who deserves it.
